AWSTemplateFormatVersion: 2010-09-09
Description: Setup one unique intances that is connected to default VPC
Parameters: 
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: AWStest 
  ImageID: 
    Type: AWS::EC2::Image::Id
    Default: ami-0dab0800aa38826f2
  ec2type: 
    Type: String
    Default: t2.micro

Resources:

  secGroupNameHTTP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-SecGrpHTTP'
      GroupDescription: 'Allow HTTP - to ALB'
      SecurityGroupIngress:
        - IpProtocol: 'TCP'
          FromPort: 80
          ToPort: 80
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-SecGrpHTTP'
# Create SecGrp ssh
  secGroupNameSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-SecGrpSSH'
      GroupDescription: 'Allow SSH - Anywhere'
      SecurityGroupIngress:
        - IpProtocol: 'TCP'
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-SecGrpSSH'

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 
        Ref: KeyName 
      ImageId: !Ref ImageID
      InstanceType: !Ref ec2type
      Monitoring: true
      IamInstanceProfile: 'CodeDeployAgentRole'
      SecurityGroupIds:
        - !Ref secGroupNameSSH
        - !Ref secGroupNameHTTP 
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install ruby -y
        wget https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install
        chmod +x ./install
        sudo ./install auto
        
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Wordpress
        - Key: Deploy
          Value: Pipe