AWSTemplateFormatVersion: 2010-09-09
Description: Creata a S3-bucket for MySQL database togther with a static Web Site Server
Parameters:

Resources:
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 
      DBInstanceClass: 
      AllowMajorVersionUpgrade: true|false
      AutoMinorVersionUpgrade: true|false
      AvailabilityZone: 
      BackupRetentionPeriod: 
      CharacterSetName: 
      DBInstanceIdentifier: 
      DBName: 
      DBParameterGroupName: 
      DBSecurityGroups: 
        - db-sg-group
      DBSnapshotIdentifier: 
      DBSubnetGroupName: 
      Engine: mysql
      EngineVersion: 
      Iops: 
      KmsKeyId: 
      LicenseModel: 
      MasterUsername: SA
      MasterUserPassword:  
      MultiAZ: true|false
      OptionGroupName: 
      Port: 
      PreferredBackupWindow: 
      PreferredMaintenanceWindow: 
      PubliclyAccessible: true|false
      SourceDBInstanceIdentifier: 
      StorageEncrypted: true|false
      StorageType: 
      VPCSecurityGroups:
        - vpc-sg-id
      Tags:
        - Key: Name
          Value: ${AWS::StackName}-DB
  