AWSTemplateFormatVersion: 2010-09-09
Description: Creata a S3-bucket for MySQL database togther with a static Web Site Server

Resources:
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mydbinstance
      DBName: "MyDB202310261431"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 50
      Engine: MySQL
      BackupRetentionPeriod: 0
      MasterUsername: admin
      MasterUserPassword: Skola123!
  